- hosts: namenode
  tasks: 
  - name: Transfering JDK and Hadoop software
    copy:
      src: "{{ item }}"
      dest: /root
    loop:
      - '/root/hadoop-1.2.1-1.x86_64.rpm'
      - "/root/jdk-8u171-linux-x64.rpm"

  - name: Installing JDK and Hadoop in Namenode
    command: 
      cmd: rpm -i jdk-8u171-linux-x64.rpm
      cmd: rpm -i hadoop-1.2.1-1.x86_64.rpm --force  
      
  - name: Creating Directory for namenode
    file:
      path: /nn
      state: directory

  - name: configuring hadoop for namenode
    template:
      src: "/ws1/hadoop/hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"

  - name: configuring hadoop for namenode
    template:
      src: "/ws1/hadoop/core-site.xml"
      dest: "/etc/hadoop/core-site.xml"

  - name: Allowing port in firewall
    firewalld:
      port: "9001/tcp"
      state: enabled
      permanent: yes
      immediate: yes
      
  - name: Formatting namenode
    command:
       cmd: hadoop namenode -format -force

  - name: Starting hadoop namenode service
    command:
       cmd: hadoop-daemon.sh start namenode




 
- hosts: datanode
  tasks:
  - name: Transfering JDK and Hadoop software
    copy:
      src: "{{ item }}"
      dest: /root
    loop:
      - "/root/hadoop-1.2.1-1.x86_64.rpm"
      - "/root/jdk-8u171-linux-x64.rpm"

  - name: Installing JDK and Hadoop in Datanode
    command:
      cmd: rpm -i jdk-8u171-linux-x64.rpm
      cmd: rpm -i hadoop-1.2.1-1.x86_64.rpm --force

  - name: Creating Directory for datanode
    file:
      path: /dn
      state: directory

  - name: configuring hadoop for datanode
    template:
      src: "/ws1/hadoop/dnode/d2"
      dest: "/etc/hadoop/hdfs-site.xml"
      
  - name: configuring hadoop for datanode
    template:
      src: "/ws1/hadoop/dnode/d"
      dest: "/etc/hadoop/core-site.xml"

  - name: Allowing port in firewall
    firewalld:
      port: "50010/tcp"
      state: enabled
      permanent: yes
      immediate: yes

  - name: Starting hadoop datanode service
    command:
       cmd: hadoop-daemon.sh start datanode
                                                                                                                                             
